import {
  BadgePercent,
  BarChart3,
  Calculator,
  FileText,
  LayoutDashboard,
  Package,
  Paintbrush,
  Settings,
  Store,
  TrendingUp,
  Users,
  WandSparkles,
} from "lucide-react";

export const ADMIN_MODULES = [
  {
    href: "/admin",
    label: "Omnifix Hub",
    shortLabel: "Hub",
    description: "Resumen operativo y accesos principales",
    icon: LayoutDashboard,
    color: "text-sky-500",
    bg: "bg-sky-500/10",
  },
  {
    href: "/admin/crm",
    label: "CRM Omnifix",
    shortLabel: "CRM",
    description: "Clientes, citas y seguimiento comercial",
    icon: BarChart3,
    color: "text-blue-500",
    bg: "bg-blue-500/10",
  },
  {
    href: "/admin/customers",
    label: "Clientes Omnifix",
    shortLabel: "Clientes",
    description: "Directorio y segmentación de clientes",
    icon: Users,
    color: "text-cyan-500",
    bg: "bg-cyan-500/10",
  },
  {
    href: "/admin/productos",
    label: "Productos Omnifix",
    shortLabel: "Productos",
    description: "Catálogo, precios y disponibilidad",
    icon: Package,
    color: "text-indigo-500",
    bg: "bg-indigo-500/10",
  },
  {
    href: "/admin/e-commerce",
    label: "E-commerce Omnifix",
    shortLabel: "E-commerce",
    description: "Vitrina Omnifix, carrito y checkout",
    icon: Store,
    color: "text-sky-500",
    bg: "bg-sky-500/10",
  },
  {
    href: "/admin/landing-builder",
    label: "Page Engine Omnifix",
    shortLabel: "Page Engine",
    description: "Motor de páginas, demos y prospectos",
    icon: WandSparkles,
    color: "text-blue-500",
    bg: "bg-blue-500/10",
  },
  {
    href: "/admin/analytics",
    label: "Analytics Omnifix",
    shortLabel: "Analytics",
    description: "Ventas, tráfico y proyecciones",
    icon: TrendingUp,
    color: "text-cyan-500",
    bg: "bg-cyan-500/10",
  },
  {
    href: "/admin/contabilidad",
    label: "F29 / SII",
    shortLabel: "F29 / SII",
    description: "SII, declaración F29 y carpeta tributaria",
    icon: Calculator,
    color: "text-blue-600",
    bg: "bg-blue-600/10",
  },
  {
    href: "/admin/beneficios",
    label: "Beneficios Fiscales",
    shortLabel: "Beneficios",
    description: "Créditos y beneficios tributarios",
    icon: BadgePercent,
    color: "text-emerald-500",
    bg: "bg-emerald-500/10",
  },
  {
    href: "/admin/cotizaciones",
    label: "Cotizaciones Omnifix",
    shortLabel: "Cotizaciones",
    description: "Propuestas, seguimiento y conversiones",
    icon: FileText,
    color: "text-cyan-500",
    bg: "bg-cyan-500/10",
  },
  {
    href: "/admin/diseno",
    label: "Diseño de marca",
    shortLabel: "Diseño",
    description: "Colores, fuentes e identidad Omnifix",
    icon: Paintbrush,
    color: "text-blue-500",
    bg: "bg-blue-500/10",
  },
  {
    href: "/admin/configuracion",
    label: "Configuración Omnifix",
    shortLabel: "Config.",
    description: "Datos, horario y métodos de pago",
    icon: Settings,
    color: "text-slate-500",
    bg: "bg-slate-500/10",
  },
] as const;

export const ADMIN_PRIMARY_NAV = ADMIN_MODULES.filter((module) =>
  [
    "/admin/crm",
    "/admin/customers",
    "/admin/productos",
    "/admin/e-commerce",
    "/admin/landing-builder",
    "/admin/analytics",
    "/admin/cotizaciones",
    "/admin/configuracion",
  ].includes(module.href),
);
